#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    # colorscheme_bg = "dark"
    colorscheme = "one"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
# user customed .
#vimcompatibility = true
    filetree_direction = "left"
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    guifont = "SauceCodePro Nerd Font Mono:h11"
    language = 'zh_CN.UTF-8'
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#python'
python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#markdown"
enableWcwidth = true
[[layers]]
name = "lang#sh"

[[layers]]
name = "colorscheme"
[[layers]]
name = "git"

[[layers]]
name = "sudo"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[custom_plugins]]
    name = "tpope/vim-fugitive"
    merged = false
